import { AlertTriangle, Scale, Gavel } from 'lucide-react';
import { motion } from 'framer-motion';

const Disclaimer = () => {
  return (
    <div style={{ maxWidth: '900px', margin: '0 auto', padding: '2rem 0' }}>
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        style={{ textAlign: 'center', marginBottom: '4rem' }}
      >
        <div style={{ display: 'inline-flex', padding: '1rem', backgroundColor: 'rgba(217, 119, 6, 0.1)', borderRadius: '20px', color: '#d97706', marginBottom: '1.5rem' }}>
          <AlertTriangle size={48} />
        </div>
        <h1 style={{ fontSize: '3rem', marginBottom: '1rem' }}>Disclaimer</h1>
        <p style={{ fontSize: '1.2rem', color: 'var(--text-muted)' }}>Important information regarding the use of our services.</p>
      </motion.div>

      <section style={{ marginBottom: '3rem' }}>
        <h2 style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1.5rem' }}>
          <Scale size={24} color="#d97706" /> 1. "As-Is" Service
        </h2>
        <p>PDFMasterstool is provided on an "as-is" and "as-available" basis. While we strive for the highest quality in document processing, we make no warranties, expressed or implied, regarding the accuracy, reliability, or completeness of the results generated by our tools.</p>
      </section>

      <section style={{ marginBottom: '3rem' }}>
        <h2 style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1.5rem' }}>
          <Gavel size={24} color="#d97706" /> 2. Limitation of Liability
        </h2>
        <p>In no event shall PDFMasterstool or its contributors be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on PDFMasterstool, even if we have been notified of the possibility of such damage.</p>
      </section>

      <section style={{ marginBottom: '3rem' }}>
        <h2>3. Local Processing Responsibility</h2>
        <p>Since PDFMasterstool operates entirely within your browser, the performance and success of document operations depend heavily on your local system's resources (CPU, RAM). We are not responsible for browser crashes, system freezes, or data loss resulting from insufficient local resources during heavy processing tasks.</p>
      </section>

      <section style={{ marginBottom: '3rem' }}>
        <h2>4. External Links</h2>
        <p>Our website may contain links to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies.</p>
      </section>

      <div className="glass" style={{ padding: '2rem', textAlign: 'center', border: '1px solid rgba(217, 119, 6, 0.2)' }}>
        <p style={{ margin: 0, fontWeight: 500 }}>By using PDFMasterstool, you hereby consent to our disclaimer and agree to its terms.</p>
      </div>
    </div>
  );
};

export default Disclaimer;

